/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20012Data struct {
	Country string `json:"country,omitempty"`
	Slug string `json:"slug,omitempty"`
	A2Code string `json:"a2_code,omitempty"`
	DialCode int32 `json:"dial_code,omitempty"`
}
