/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2004 struct {
	// The status of the API request
	Status string `json:"status,omitempty"`
	// The faxes received by a certain user
	Inbox []InlineResponse2004Inbox `json:"inbox,omitempty"`
	Meta *InlineResponse2004Meta `json:"meta,omitempty"`
}
