/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20014Areacodes struct {
	CountryCode string `json:"country_code,omitempty"`
	StateId int32 `json:"state_id,omitempty"`
	AreaCode string `json:"area_code,omitempty"`
}
