/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20017Numbers struct {
	Id int32 `json:"id,omitempty"`
	OrderReference string `json:"order_reference,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Country string `json:"country,omitempty"`
	CityName string `json:"city_name,omitempty"`
	AreaCode string `json:"area_code,omitempty"`
	DidGroupId int32 `json:"did_group_id,omitempty"`
	DidNumber string `json:"did_number,omitempty"`
	ExpirationDate string `json:"expiration_date,omitempty"`
	Status string `json:"status,omitempty"`
}
