/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20013 struct {
	// The status of the API request
	Status string `json:"status,omitempty"`
	// States data
	States []InlineResponse20013States `json:"states,omitempty"`
}
