/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2008Files struct {
	Id int32 `json:"id,omitempty"`
	Filename string `json:"filename,omitempty"`
	Pages int32 `json:"pages,omitempty"`
	Size int32 `json:"size,omitempty"`
	Uploaded string `json:"uploaded,omitempty"`
}
