/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20016Data struct {
	Id int32 `json:"id,omitempty"`
	DidId int32 `json:"did_id,omitempty"`
	DidGroupId int32 `json:"did_group_id,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	CityName string `json:"city_name,omitempty"`
	AreaCode string `json:"area_code,omitempty"`
	Number string `json:"number,omitempty"`
	Type_ string `json:"type,omitempty"`
	TrunkId int32 `json:"trunk_id,omitempty"`
}
