/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse200 struct {
	// The status of the API request
	Status string `json:"status,omitempty"`
	// The id of the fax job. It is used to check the status of the fax job.
	FaxJobId int32 `json:"fax_job_id,omitempty"`
	// The remaining cash balance
	UserCashBalance float32 `json:"user_cash_balance,omitempty"`
	// The cost of sending fax
	Cost float32 `json:"cost,omitempty"`
}
