/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Contains the paginations links
type InlineResponse2004Meta struct {
	Pagination *InlineResponse2004MetaPagination `json:"pagination,omitempty"`
}
