/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The pagination data
type InlineResponse2004MetaPagination struct {
	Total int32 `json:"total,omitempty"`
	Count int32 `json:"count,omitempty"`
	PerPage int32 `json:"per_page,omitempty"`
	CurrentPage int32 `json:"current_page,omitempty"`
	TotalPages int32 `json:"total_pages,omitempty"`
	Links *InlineResponse2004MetaPaginationLinks `json:"links,omitempty"`
}
