/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2004Inbox struct {
	Id int32 `json:"id,omitempty"`
	DidId int32 `json:"did_id,omitempty"`
	Filename string `json:"filename,omitempty"`
	Filesize string `json:"filesize,omitempty"`
	Number string `json:"number,omitempty"`
	Sender string `json:"sender,omitempty"`
	TotalPages int32 `json:"total_pages,omitempty"`
	CreatedAt *InlineResponse2003Created `json:"created_at,omitempty"`
	PreviewFile string `json:"preview_file,omitempty"`
	FileUrl string `json:"file_url,omitempty"`
}
