/*
 * Fax.to REST API client for Go
 *
 * This is Fax.to REST API client for Go.
 *
 * API version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse20015Data struct {
	DidGroupId int32 `json:"did_group_id,omitempty"`
	AreaCode string `json:"area_code,omitempty"`
	CityName string `json:"city_name,omitempty"`
}
